// Package schedulertransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package schedulertransport

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExecutionStatus.
const (
	Failed    ExecutionStatus = "failed"
	Succeeded ExecutionStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for ParameterKind.
const (
	Boolean ParameterKind = "boolean"
	Integer ParameterKind = "integer"
	String  ParameterKind = "string"
)

// Valid indicates whether the value is a known member of the ParameterKind enum.
func (e ParameterKind) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Integer:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// Definition defines model for Definition.
type Definition struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	NextRunAt  *time.Time         `json:"nextRunAt,omitempty"`
	Parameters Parameters         `json:"parameters"`
	Revision   int                `json:"revision"`
	Schedule   Schedule           `json:"schedule"`
	TaskType   string             `json:"taskType"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// DefinitionInput defines model for DefinitionInput.
type DefinitionInput struct {
	Name       string     `json:"name"`
	Parameters Parameters `json:"parameters"`
	Schedule   Schedule   `json:"schedule"`
	TaskType   string     `json:"taskType"`
}

// DefinitionPage defines model for DefinitionPage.
type DefinitionPage struct {
	Rows  []Definition `json:"rows"`
	Total int          `json:"total"`
}

// Execution defines model for Execution.
type Execution struct {
	DefinitionId       openapi_types.UUID `json:"definitionId"`
	DefinitionRevision int                `json:"definitionRevision"`
	ErrorCode          *string            `json:"errorCode,omitempty"`
	ExecutorOwner      string             `json:"executorOwner"`
	FinishedAt         time.Time          `json:"finishedAt"`
	Id                 openapi_types.UUID `json:"id"`
	ScheduledFor       time.Time          `json:"scheduledFor"`
	StartedAt          time.Time          `json:"startedAt"`
	Status             ExecutionStatus    `json:"status"`
	TaskType           string             `json:"taskType"`
}

// ExecutionPage defines model for ExecutionPage.
type ExecutionPage struct {
	Rows  []Execution `json:"rows"`
	Total int         `json:"total"`
}

// ExecutionStatus defines model for ExecutionStatus.
type ExecutionStatus string

// ParameterField defines model for ParameterField.
type ParameterField struct {
	AllowedValues *[]string     `json:"allowedValues,omitempty"`
	Kind          ParameterKind `json:"kind"`
	Label         string        `json:"label"`
	Maximum       *int          `json:"maximum,omitempty"`
	Minimum       *int          `json:"minimum,omitempty"`
	Name          string        `json:"name"`
	Required      bool          `json:"required"`
}

// ParameterKind defines model for ParameterKind.
type ParameterKind string

// ParameterValue defines model for ParameterValue.
type ParameterValue struct {
	union json.RawMessage
}

// ParameterValue0 defines model for ParameterValue.0.
type ParameterValue0 = string

// ParameterValue1 defines model for ParameterValue.1.
type ParameterValue1 = int

// ParameterValue2 defines model for ParameterValue.2.
type ParameterValue2 = bool

// Parameters defines model for Parameters.
type Parameters map[string]ParameterValue

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// RevisionRequest defines model for RevisionRequest.
type RevisionRequest struct {
	Revision int `json:"revision"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// Cron 标准五段 Cron 表达式
	Cron     string `json:"cron"`
	Timezone string `json:"timezone"`
}

// TaskType defines model for TaskType.
type TaskType struct {
	Fields []ParameterField `json:"fields"`
	Key    string           `json:"key"`
	Label  string           `json:"label"`
}

// UpdateDefinitionRequest defines model for UpdateDefinitionRequest.
type UpdateDefinitionRequest struct {
	Name       string     `json:"name"`
	Parameters Parameters `json:"parameters"`
	Revision   int        `json:"revision"`
	Schedule   Schedule   `json:"schedule"`
	TaskType   string     `json:"taskType"`
}

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// DefinitionId defines model for DefinitionId.
type DefinitionId = openapi_types.UUID

// Revision defines model for Revision.
type Revision = int

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ListSchedulerDefinitionsParams defines parameters for ListSchedulerDefinitions.
type ListSchedulerDefinitionsParams struct {
	Search   *string `form:"search,omitempty" json:"search,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// DeleteSchedulerDefinitionParams defines parameters for DeleteSchedulerDefinition.
type DeleteSchedulerDefinitionParams struct {
	Revision Revision `form:"revision" json:"revision"`
}

// ListSchedulerExecutionsParams defines parameters for ListSchedulerExecutions.
type ListSchedulerExecutionsParams struct {
	DefinitionId *openapi_types.UUID `form:"definitionId,omitempty" json:"definitionId,omitempty"`
	Status       *ExecutionStatus    `form:"status,omitempty" json:"status,omitempty"`
	Page         *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize     *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateSchedulerDefinitionJSONRequestBody defines body for CreateSchedulerDefinition for application/json ContentType.
type CreateSchedulerDefinitionJSONRequestBody = DefinitionInput

// UpdateSchedulerDefinitionJSONRequestBody defines body for UpdateSchedulerDefinition for application/json ContentType.
type UpdateSchedulerDefinitionJSONRequestBody = UpdateDefinitionRequest

// EnableSchedulerDefinitionJSONRequestBody defines body for EnableSchedulerDefinition for application/json ContentType.
type EnableSchedulerDefinitionJSONRequestBody = RevisionRequest

// RunSchedulerDefinitionJSONRequestBody defines body for RunSchedulerDefinition for application/json ContentType.
type RunSchedulerDefinitionJSONRequestBody = RevisionRequest

// StopSchedulerDefinitionJSONRequestBody defines body for StopSchedulerDefinition for application/json ContentType.
type StopSchedulerDefinitionJSONRequestBody = RevisionRequest

// AsParameterValue0 returns the union data inside the ParameterValue as a ParameterValue0
func (t ParameterValue) AsParameterValue0() (ParameterValue0, error) {
	var body ParameterValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterValue0 overwrites any union data inside the ParameterValue as the provided ParameterValue0
func (t *ParameterValue) FromParameterValue0(v ParameterValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterValue0 performs a merge with any union data inside the ParameterValue, using the provided ParameterValue0
func (t *ParameterValue) MergeParameterValue0(v ParameterValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterValue1 returns the union data inside the ParameterValue as a ParameterValue1
func (t ParameterValue) AsParameterValue1() (ParameterValue1, error) {
	var body ParameterValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterValue1 overwrites any union data inside the ParameterValue as the provided ParameterValue1
func (t *ParameterValue) FromParameterValue1(v ParameterValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterValue1 performs a merge with any union data inside the ParameterValue, using the provided ParameterValue1
func (t *ParameterValue) MergeParameterValue1(v ParameterValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterValue2 returns the union data inside the ParameterValue as a ParameterValue2
func (t ParameterValue) AsParameterValue2() (ParameterValue2, error) {
	var body ParameterValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterValue2 overwrites any union data inside the ParameterValue as the provided ParameterValue2
func (t *ParameterValue) FromParameterValue2(v ParameterValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterValue2 performs a merge with any union data inside the ParameterValue, using the provided ParameterValue2
func (t *ParameterValue) MergeParameterValue2(v ParameterValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ParameterValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ParameterValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListSchedulerDefinitions List task definitions
	// (GET /scheduler/definitions)
	ListSchedulerDefinitions(w http.ResponseWriter, r *http.Request, params ListSchedulerDefinitionsParams)
	// CreateSchedulerDefinition Create a disabled task definition
	// (POST /scheduler/definitions)
	CreateSchedulerDefinition(w http.ResponseWriter, r *http.Request)
	// DeleteSchedulerDefinition Stop and tombstone a task definition
	// (DELETE /scheduler/definitions/{definitionId})
	DeleteSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId, params DeleteSchedulerDefinitionParams)
	// UpdateSchedulerDefinition Update a stopped task definition
	// (PATCH /scheduler/definitions/{definitionId})
	UpdateSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId)
	// EnableSchedulerDefinition Enable a task definition from its next UTC occurrence
	// (POST /scheduler/definitions/{definitionId}/enable)
	EnableSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId)
	// RunSchedulerDefinition Queue one execution of a registered task
	// (POST /scheduler/definitions/{definitionId}/run)
	RunSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId)
	// StopSchedulerDefinition Stop a task definition at the row-lock linearization point
	// (POST /scheduler/definitions/{definitionId}/stop)
	StopSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId)
	// ListSchedulerExecutions List redacted execution history
	// (GET /scheduler/executions)
	ListSchedulerExecutions(w http.ResponseWriter, r *http.Request, params ListSchedulerExecutionsParams)
	// ListSchedulerTaskTypes List compile-time registered task types
	// (GET /scheduler/task-types)
	ListSchedulerTaskTypes(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListSchedulerDefinitions List task definitions
// (GET /scheduler/definitions)
func (_ Unimplemented) ListSchedulerDefinitions(w http.ResponseWriter, r *http.Request, params ListSchedulerDefinitionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateSchedulerDefinition Create a disabled task definition
// (POST /scheduler/definitions)
func (_ Unimplemented) CreateSchedulerDefinition(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteSchedulerDefinition Stop and tombstone a task definition
// (DELETE /scheduler/definitions/{definitionId})
func (_ Unimplemented) DeleteSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId, params DeleteSchedulerDefinitionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateSchedulerDefinition Update a stopped task definition
// (PATCH /scheduler/definitions/{definitionId})
func (_ Unimplemented) UpdateSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// EnableSchedulerDefinition Enable a task definition from its next UTC occurrence
// (POST /scheduler/definitions/{definitionId}/enable)
func (_ Unimplemented) EnableSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RunSchedulerDefinition Queue one execution of a registered task
// (POST /scheduler/definitions/{definitionId}/run)
func (_ Unimplemented) RunSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StopSchedulerDefinition Stop a task definition at the row-lock linearization point
// (POST /scheduler/definitions/{definitionId}/stop)
func (_ Unimplemented) StopSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListSchedulerExecutions List redacted execution history
// (GET /scheduler/executions)
func (_ Unimplemented) ListSchedulerExecutions(w http.ResponseWriter, r *http.Request, params ListSchedulerExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListSchedulerTaskTypes List compile-time registered task types
// (GET /scheduler/task-types)
func (_ Unimplemented) ListSchedulerTaskTypes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSchedulerDefinitions operation middleware
func (siw *ServerInterfaceWrapper) ListSchedulerDefinitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulerDefinitionsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedulerDefinitions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedulerDefinition(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "definitionId" -------------
	var definitionId DefinitionId

	err = runtime.BindStyledParameterWithOptions("simple", "definitionId", chi.URLParam(r, "definitionId"), &definitionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSchedulerDefinitionParams

	// ------------- Required query parameter "revision" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "revision", r.URL.Query(), &params.Revision, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "revision"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revision", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedulerDefinition(w, r, definitionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "definitionId" -------------
	var definitionId DefinitionId

	err = runtime.BindStyledParameterWithOptions("simple", "definitionId", chi.URLParam(r, "definitionId"), &definitionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedulerDefinition(w, r, definitionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnableSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) EnableSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "definitionId" -------------
	var definitionId DefinitionId

	err = runtime.BindStyledParameterWithOptions("simple", "definitionId", chi.URLParam(r, "definitionId"), &definitionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnableSchedulerDefinition(w, r, definitionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) RunSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "definitionId" -------------
	var definitionId DefinitionId

	err = runtime.BindStyledParameterWithOptions("simple", "definitionId", chi.URLParam(r, "definitionId"), &definitionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunSchedulerDefinition(w, r, definitionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopSchedulerDefinition operation middleware
func (siw *ServerInterfaceWrapper) StopSchedulerDefinition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "definitionId" -------------
	var definitionId DefinitionId

	err = runtime.BindStyledParameterWithOptions("simple", "definitionId", chi.URLParam(r, "definitionId"), &definitionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopSchedulerDefinition(w, r, definitionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedulerExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListSchedulerExecutions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulerExecutionsParams

	// ------------- Optional query parameter "definitionId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "definitionId", r.URL.Query(), &params.DefinitionId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "definitionId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "definitionId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedulerExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedulerTaskTypes operation middleware
func (siw *ServerInterfaceWrapper) ListSchedulerTaskTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedulerTaskTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scheduler/definitions", wrapper.ListSchedulerDefinitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scheduler/definitions", wrapper.CreateSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/scheduler/definitions/{definitionId}", wrapper.DeleteSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/scheduler/definitions/{definitionId}", wrapper.UpdateSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scheduler/definitions/{definitionId}/enable", wrapper.EnableSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scheduler/definitions/{definitionId}/run", wrapper.RunSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scheduler/definitions/{definitionId}/stop", wrapper.StopSchedulerDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scheduler/executions", wrapper.ListSchedulerExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scheduler/task-types", wrapper.ListSchedulerTaskTypes)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type AuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizationProblemResponseHeaders
}

type ConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type ConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictProblemResponseHeaders
}

type InternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type InternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalProblemResponseHeaders
}

type NotFoundProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type NotFoundProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers NotFoundProblemResponseHeaders
}

type ValidationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type ValidationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ValidationProblemResponseHeaders
}

type ListSchedulerDefinitionsRequestObject struct {
	Params ListSchedulerDefinitionsParams
}

type ListSchedulerDefinitionsResponseObject interface {
	VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error
}

type ListSchedulerDefinitions200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type ListSchedulerDefinitions200JSONResponse struct {
	Body    DefinitionPage
	Headers ListSchedulerDefinitions200ResponseHeaders
}

func (response ListSchedulerDefinitions200JSONResponse) VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerDefinitions400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerDefinitions400ApplicationProblemPlusJSONResponse) VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerDefinitions401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerDefinitions401ApplicationProblemPlusJSONResponse) VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerDefinitions403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerDefinitions403ApplicationProblemPlusJSONResponse) VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerDefinitions500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerDefinitions500ApplicationProblemPlusJSONResponse) VisitListSchedulerDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinitionRequestObject struct {
	Body *CreateSchedulerDefinitionJSONRequestBody
}

type CreateSchedulerDefinitionResponseObject interface {
	VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type CreateSchedulerDefinition201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type CreateSchedulerDefinition201JSONResponse struct {
	Body    Definition
	Headers CreateSchedulerDefinition201ResponseHeaders
}

func (response CreateSchedulerDefinition201JSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response CreateSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response CreateSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response CreateSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response CreateSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response CreateSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitCreateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinitionRequestObject struct {
	DefinitionId DefinitionId `json:"definitionId"`
	Params       DeleteSchedulerDefinitionParams
}

type DeleteSchedulerDefinitionResponseObject interface {
	VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type DeleteSchedulerDefinition204ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type DeleteSchedulerDefinition204Response struct {
	Headers DeleteSchedulerDefinition204ResponseHeaders
}

func (response DeleteSchedulerDefinition204Response) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(204)
	return nil
}

type DeleteSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition404ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DeleteSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitDeleteSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinitionRequestObject struct {
	DefinitionId DefinitionId `json:"definitionId"`
	Body         *UpdateSchedulerDefinitionJSONRequestBody
}

type UpdateSchedulerDefinitionResponseObject interface {
	VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type UpdateSchedulerDefinition200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type UpdateSchedulerDefinition200JSONResponse struct {
	Body    Definition
	Headers UpdateSchedulerDefinition200ResponseHeaders
}

func (response UpdateSchedulerDefinition200JSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition404ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UpdateSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitUpdateSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinitionRequestObject struct {
	DefinitionId DefinitionId `json:"definitionId"`
	Body         *EnableSchedulerDefinitionJSONRequestBody
}

type EnableSchedulerDefinitionResponseObject interface {
	VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type EnableSchedulerDefinition200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type EnableSchedulerDefinition200JSONResponse struct {
	Body    Definition
	Headers EnableSchedulerDefinition200ResponseHeaders
}

func (response EnableSchedulerDefinition200JSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition404ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EnableSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response EnableSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitEnableSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinitionRequestObject struct {
	DefinitionId DefinitionId `json:"definitionId"`
	Body         *RunSchedulerDefinitionJSONRequestBody
}

type RunSchedulerDefinitionResponseObject interface {
	VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type RunSchedulerDefinition202ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type RunSchedulerDefinition202JSONResponse struct {
	Body struct {
		ExecutionId openapi_types.UUID `json:"executionId"`
	}
	Headers RunSchedulerDefinition202ResponseHeaders
}

func (response RunSchedulerDefinition202JSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition404ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RunSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response RunSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitRunSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinitionRequestObject struct {
	DefinitionId DefinitionId `json:"definitionId"`
	Body         *StopSchedulerDefinitionJSONRequestBody
}

type StopSchedulerDefinitionResponseObject interface {
	VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error
}

type StopSchedulerDefinition200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type StopSchedulerDefinition200JSONResponse struct {
	Body    Definition
	Headers StopSchedulerDefinition200ResponseHeaders
}

func (response StopSchedulerDefinition200JSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition400ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition401ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition403ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition404ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition409ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopSchedulerDefinition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response StopSchedulerDefinition500ApplicationProblemPlusJSONResponse) VisitStopSchedulerDefinitionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerExecutionsRequestObject struct {
	Params ListSchedulerExecutionsParams
}

type ListSchedulerExecutionsResponseObject interface {
	VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error
}

type ListSchedulerExecutions200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type ListSchedulerExecutions200JSONResponse struct {
	Body    ExecutionPage
	Headers ListSchedulerExecutions200ResponseHeaders
}

func (response ListSchedulerExecutions200JSONResponse) VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerExecutions400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerExecutions400ApplicationProblemPlusJSONResponse) VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerExecutions401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerExecutions401ApplicationProblemPlusJSONResponse) VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerExecutions403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerExecutions403ApplicationProblemPlusJSONResponse) VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerExecutions500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerExecutions500ApplicationProblemPlusJSONResponse) VisitListSchedulerExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerTaskTypesRequestObject struct {
}

type ListSchedulerTaskTypesResponseObject interface {
	VisitListSchedulerTaskTypesResponse(w http.ResponseWriter) error
}

type ListSchedulerTaskTypes200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type ListSchedulerTaskTypes200JSONResponse struct {
	Body    []TaskType
	Headers ListSchedulerTaskTypes200ResponseHeaders
}

func (response ListSchedulerTaskTypes200JSONResponse) VisitListSchedulerTaskTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerTaskTypes401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerTaskTypes401ApplicationProblemPlusJSONResponse) VisitListSchedulerTaskTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerTaskTypes403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerTaskTypes403ApplicationProblemPlusJSONResponse) VisitListSchedulerTaskTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulerTaskTypes500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListSchedulerTaskTypes500ApplicationProblemPlusJSONResponse) VisitListSchedulerTaskTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListSchedulerDefinitions List task definitions
	// (GET /scheduler/definitions)
	ListSchedulerDefinitions(ctx context.Context, request ListSchedulerDefinitionsRequestObject) (ListSchedulerDefinitionsResponseObject, error)
	// CreateSchedulerDefinition Create a disabled task definition
	// (POST /scheduler/definitions)
	CreateSchedulerDefinition(ctx context.Context, request CreateSchedulerDefinitionRequestObject) (CreateSchedulerDefinitionResponseObject, error)
	// DeleteSchedulerDefinition Stop and tombstone a task definition
	// (DELETE /scheduler/definitions/{definitionId})
	DeleteSchedulerDefinition(ctx context.Context, request DeleteSchedulerDefinitionRequestObject) (DeleteSchedulerDefinitionResponseObject, error)
	// UpdateSchedulerDefinition Update a stopped task definition
	// (PATCH /scheduler/definitions/{definitionId})
	UpdateSchedulerDefinition(ctx context.Context, request UpdateSchedulerDefinitionRequestObject) (UpdateSchedulerDefinitionResponseObject, error)
	// EnableSchedulerDefinition Enable a task definition from its next UTC occurrence
	// (POST /scheduler/definitions/{definitionId}/enable)
	EnableSchedulerDefinition(ctx context.Context, request EnableSchedulerDefinitionRequestObject) (EnableSchedulerDefinitionResponseObject, error)
	// RunSchedulerDefinition Queue one execution of a registered task
	// (POST /scheduler/definitions/{definitionId}/run)
	RunSchedulerDefinition(ctx context.Context, request RunSchedulerDefinitionRequestObject) (RunSchedulerDefinitionResponseObject, error)
	// StopSchedulerDefinition Stop a task definition at the row-lock linearization point
	// (POST /scheduler/definitions/{definitionId}/stop)
	StopSchedulerDefinition(ctx context.Context, request StopSchedulerDefinitionRequestObject) (StopSchedulerDefinitionResponseObject, error)
	// ListSchedulerExecutions List redacted execution history
	// (GET /scheduler/executions)
	ListSchedulerExecutions(ctx context.Context, request ListSchedulerExecutionsRequestObject) (ListSchedulerExecutionsResponseObject, error)
	// ListSchedulerTaskTypes List compile-time registered task types
	// (GET /scheduler/task-types)
	ListSchedulerTaskTypes(ctx context.Context, request ListSchedulerTaskTypesRequestObject) (ListSchedulerTaskTypesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSchedulerDefinitions operation middleware
func (sh *strictHandler) ListSchedulerDefinitions(w http.ResponseWriter, r *http.Request, params ListSchedulerDefinitionsParams) {
	var request ListSchedulerDefinitionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedulerDefinitions(ctx, request.(ListSchedulerDefinitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedulerDefinitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulerDefinitionsResponseObject); ok {
		if err := validResponse.VisitListSchedulerDefinitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSchedulerDefinition operation middleware
func (sh *strictHandler) CreateSchedulerDefinition(w http.ResponseWriter, r *http.Request) {
	var request CreateSchedulerDefinitionRequestObject

	var body CreateSchedulerDefinitionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSchedulerDefinition(ctx, request.(CreateSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitCreateSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchedulerDefinition operation middleware
func (sh *strictHandler) DeleteSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId, params DeleteSchedulerDefinitionParams) {
	var request DeleteSchedulerDefinitionRequestObject

	request.DefinitionId = definitionId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchedulerDefinition(ctx, request.(DeleteSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitDeleteSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSchedulerDefinition operation middleware
func (sh *strictHandler) UpdateSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	var request UpdateSchedulerDefinitionRequestObject

	request.DefinitionId = definitionId

	var body UpdateSchedulerDefinitionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSchedulerDefinition(ctx, request.(UpdateSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitUpdateSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnableSchedulerDefinition operation middleware
func (sh *strictHandler) EnableSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	var request EnableSchedulerDefinitionRequestObject

	request.DefinitionId = definitionId

	var body EnableSchedulerDefinitionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnableSchedulerDefinition(ctx, request.(EnableSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnableSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnableSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitEnableSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunSchedulerDefinition operation middleware
func (sh *strictHandler) RunSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	var request RunSchedulerDefinitionRequestObject

	request.DefinitionId = definitionId

	var body RunSchedulerDefinitionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunSchedulerDefinition(ctx, request.(RunSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitRunSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopSchedulerDefinition operation middleware
func (sh *strictHandler) StopSchedulerDefinition(w http.ResponseWriter, r *http.Request, definitionId DefinitionId) {
	var request StopSchedulerDefinitionRequestObject

	request.DefinitionId = definitionId

	var body StopSchedulerDefinitionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopSchedulerDefinition(ctx, request.(StopSchedulerDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopSchedulerDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopSchedulerDefinitionResponseObject); ok {
		if err := validResponse.VisitStopSchedulerDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedulerExecutions operation middleware
func (sh *strictHandler) ListSchedulerExecutions(w http.ResponseWriter, r *http.Request, params ListSchedulerExecutionsParams) {
	var request ListSchedulerExecutionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedulerExecutions(ctx, request.(ListSchedulerExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedulerExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulerExecutionsResponseObject); ok {
		if err := validResponse.VisitListSchedulerExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedulerTaskTypes operation middleware
func (sh *strictHandler) ListSchedulerTaskTypes(w http.ResponseWriter, r *http.Request) {
	var request ListSchedulerTaskTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedulerTaskTypes(ctx, request.(ListSchedulerTaskTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedulerTaskTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulerTaskTypesResponseObject); ok {
		if err := validResponse.VisitListSchedulerTaskTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
