// Package sessiontransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sessiontransport

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// Profile defines model for Profile.
type Profile struct {
	AvatarRef   *string             `json:"avatarRef,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          string              `json:"id"`
	Username    string              `json:"username"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	CsrfToken string  `json:"csrfToken"`
	Profile   Profile `json:"profile"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	AvatarRef   *string             `json:"avatarRef,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
}

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// RateLimitProblem defines model for RateLimitProblem.
type RateLimitProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ChangeIamAccountPasswordJSONRequestBody defines body for ChangeIamAccountPassword for application/json ContentType.
type ChangeIamAccountPasswordJSONRequestBody = ChangePasswordRequest

// UpdateIamAccountProfileJSONRequestBody defines body for UpdateIamAccountProfile for application/json ContentType.
type UpdateIamAccountProfileJSONRequestBody = UpdateProfileRequest

// LoginIamSessionJSONRequestBody defines body for LoginIamSession for application/json ContentType.
type LoginIamSessionJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ChangeIamAccountPassword Replace the authenticated account password
	// (PUT /iam/account/password)
	ChangeIamAccountPassword(w http.ResponseWriter, r *http.Request)
	// GetIamAccountProfile Read the authenticated account profile
	// (GET /iam/account/profile)
	GetIamAccountProfile(w http.ResponseWriter, r *http.Request)
	// UpdateIamAccountProfile Update the authenticated account profile
	// (PATCH /iam/account/profile)
	UpdateIamAccountProfile(w http.ResponseWriter, r *http.Request)
	// GetCurrentIamSession Read the current session without mutating it
	// (GET /iam/session/current)
	GetCurrentIamSession(w http.ResponseWriter, r *http.Request)
	// HeartbeatIamSession Extend idle expiry for an active session
	// (POST /iam/session/heartbeat)
	HeartbeatIamSession(w http.ResponseWriter, r *http.Request)
	// LoginIamSession Start an authenticated session
	// (POST /iam/session/login)
	LoginIamSession(w http.ResponseWriter, r *http.Request)
	// LogoutIamSession Revoke the current session
	// (POST /iam/session/logout)
	LogoutIamSession(w http.ResponseWriter, r *http.Request)
	// RenewIamSession Renew an active session while preserving its family CSRF token
	// (POST /iam/session/renew)
	RenewIamSession(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ChangeIamAccountPassword Replace the authenticated account password
// (PUT /iam/account/password)
func (_ Unimplemented) ChangeIamAccountPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetIamAccountProfile Read the authenticated account profile
// (GET /iam/account/profile)
func (_ Unimplemented) GetIamAccountProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateIamAccountProfile Update the authenticated account profile
// (PATCH /iam/account/profile)
func (_ Unimplemented) UpdateIamAccountProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentIamSession Read the current session without mutating it
// (GET /iam/session/current)
func (_ Unimplemented) GetCurrentIamSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HeartbeatIamSession Extend idle expiry for an active session
// (POST /iam/session/heartbeat)
func (_ Unimplemented) HeartbeatIamSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LoginIamSession Start an authenticated session
// (POST /iam/session/login)
func (_ Unimplemented) LoginIamSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutIamSession Revoke the current session
// (POST /iam/session/logout)
func (_ Unimplemented) LogoutIamSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RenewIamSession Renew an active session while preserving its family CSRF token
// (POST /iam/session/renew)
func (_ Unimplemented) RenewIamSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChangeIamAccountPassword operation middleware
func (siw *ServerInterfaceWrapper) ChangeIamAccountPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeIamAccountPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIamAccountProfile operation middleware
func (siw *ServerInterfaceWrapper) GetIamAccountProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIamAccountProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIamAccountProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateIamAccountProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIamAccountProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentIamSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentIamSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentIamSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeartbeatIamSession operation middleware
func (siw *ServerInterfaceWrapper) HeartbeatIamSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeartbeatIamSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginIamSession operation middleware
func (siw *ServerInterfaceWrapper) LoginIamSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginIamSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutIamSession operation middleware
func (siw *ServerInterfaceWrapper) LogoutIamSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutIamSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenewIamSession operation middleware
func (siw *ServerInterfaceWrapper) RenewIamSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenewIamSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/iam/account/password", wrapper.ChangeIamAccountPassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/iam/account/profile", wrapper.GetIamAccountProfile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/iam/account/profile", wrapper.UpdateIamAccountProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/iam/session/current", wrapper.GetCurrentIamSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/iam/session/heartbeat", wrapper.HeartbeatIamSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/iam/session/login", wrapper.LoginIamSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/iam/session/logout", wrapper.LogoutIamSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/iam/session/renew", wrapper.RenewIamSession)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemApplicationProblemPlusJSONResponse Problem

type ConflictProblemApplicationProblemPlusJSONResponse Problem

type InternalProblemApplicationProblemPlusJSONResponse Problem

type RateLimitProblemResponseHeaders struct {
	RetryAfter int
}
type RateLimitProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers RateLimitProblemResponseHeaders
}

type ValidationProblemApplicationProblemPlusJSONResponse Problem

type ChangeIamAccountPasswordRequestObject struct {
	Body *ChangeIamAccountPasswordJSONRequestBody
}

type ChangeIamAccountPasswordResponseObject interface {
	VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error
}

type ChangeIamAccountPassword204ResponseHeaders struct {
	SetCookie *string
}

type ChangeIamAccountPassword204Response struct {
	Headers ChangeIamAccountPassword204ResponseHeaders
}

func (response ChangeIamAccountPassword204Response) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type ChangeIamAccountPassword400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ChangeIamAccountPassword400ApplicationProblemPlusJSONResponse) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeIamAccountPassword401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ChangeIamAccountPassword401ApplicationProblemPlusJSONResponse) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeIamAccountPassword403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ChangeIamAccountPassword403ApplicationProblemPlusJSONResponse) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeIamAccountPassword409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response ChangeIamAccountPassword409ApplicationProblemPlusJSONResponse) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeIamAccountPassword500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ChangeIamAccountPassword500ApplicationProblemPlusJSONResponse) VisitChangeIamAccountPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetIamAccountProfileRequestObject struct {
}

type GetIamAccountProfileResponseObject interface {
	VisitGetIamAccountProfileResponse(w http.ResponseWriter) error
}

type GetIamAccountProfile200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetIamAccountProfile200JSONResponse struct {
	Body    Profile
	Headers GetIamAccountProfile200ResponseHeaders
}

func (response GetIamAccountProfile200JSONResponse) VisitGetIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetIamAccountProfile401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetIamAccountProfile401ApplicationProblemPlusJSONResponse) VisitGetIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetIamAccountProfile500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetIamAccountProfile500ApplicationProblemPlusJSONResponse) VisitGetIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfileRequestObject struct {
	Body *UpdateIamAccountProfileJSONRequestBody
}

type UpdateIamAccountProfileResponseObject interface {
	VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error
}

type UpdateIamAccountProfile200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type UpdateIamAccountProfile200JSONResponse struct {
	Body    Profile
	Headers UpdateIamAccountProfile200ResponseHeaders
}

func (response UpdateIamAccountProfile200JSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfile400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateIamAccountProfile400ApplicationProblemPlusJSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfile401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateIamAccountProfile401ApplicationProblemPlusJSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfile403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateIamAccountProfile403ApplicationProblemPlusJSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfile409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UpdateIamAccountProfile409ApplicationProblemPlusJSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateIamAccountProfile500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UpdateIamAccountProfile500ApplicationProblemPlusJSONResponse) VisitUpdateIamAccountProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentIamSessionRequestObject struct {
}

type GetCurrentIamSessionResponseObject interface {
	VisitGetCurrentIamSessionResponse(w http.ResponseWriter) error
}

type GetCurrentIamSession200ResponseHeaders struct {
	XCSRFToken string
}

type GetCurrentIamSession200JSONResponse struct {
	Body    SessionResponse
	Headers GetCurrentIamSession200ResponseHeaders
}

func (response GetCurrentIamSession200JSONResponse) VisitGetCurrentIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentIamSession401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetCurrentIamSession401ApplicationProblemPlusJSONResponse) VisitGetCurrentIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentIamSession500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetCurrentIamSession500ApplicationProblemPlusJSONResponse) VisitGetCurrentIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatIamSessionRequestObject struct {
}

type HeartbeatIamSessionResponseObject interface {
	VisitHeartbeatIamSessionResponse(w http.ResponseWriter) error
}

type HeartbeatIamSession200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type HeartbeatIamSession200JSONResponse struct {
	Body    SessionResponse
	Headers HeartbeatIamSession200ResponseHeaders
}

func (response HeartbeatIamSession200JSONResponse) VisitHeartbeatIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatIamSession401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response HeartbeatIamSession401ApplicationProblemPlusJSONResponse) VisitHeartbeatIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatIamSession403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response HeartbeatIamSession403ApplicationProblemPlusJSONResponse) VisitHeartbeatIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatIamSession500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response HeartbeatIamSession500ApplicationProblemPlusJSONResponse) VisitHeartbeatIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LoginIamSessionRequestObject struct {
	Body *LoginIamSessionJSONRequestBody
}

type LoginIamSessionResponseObject interface {
	VisitLoginIamSessionResponse(w http.ResponseWriter) error
}

type LoginIamSession200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type LoginIamSession200JSONResponse struct {
	Body    SessionResponse
	Headers LoginIamSession200ResponseHeaders
}

func (response LoginIamSession200JSONResponse) VisitLoginIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginIamSession400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response LoginIamSession400ApplicationProblemPlusJSONResponse) VisitLoginIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginIamSession401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response LoginIamSession401ApplicationProblemPlusJSONResponse) VisitLoginIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginIamSession429ApplicationProblemPlusJSONResponse struct {
	RateLimitProblemApplicationProblemPlusJSONResponse
}

func (response LoginIamSession429ApplicationProblemPlusJSONResponse) VisitLoginIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LoginIamSession500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response LoginIamSession500ApplicationProblemPlusJSONResponse) VisitLoginIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutIamSessionRequestObject struct {
}

type LogoutIamSessionResponseObject interface {
	VisitLogoutIamSessionResponse(w http.ResponseWriter) error
}

type LogoutIamSession204ResponseHeaders struct {
	SetCookie *string
}

type LogoutIamSession204Response struct {
	Headers LogoutIamSession204ResponseHeaders
}

func (response LogoutIamSession204Response) VisitLogoutIamSessionResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutIamSession401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response LogoutIamSession401ApplicationProblemPlusJSONResponse) VisitLogoutIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutIamSession403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response LogoutIamSession403ApplicationProblemPlusJSONResponse) VisitLogoutIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutIamSession500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response LogoutIamSession500ApplicationProblemPlusJSONResponse) VisitLogoutIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RenewIamSessionRequestObject struct {
}

type RenewIamSessionResponseObject interface {
	VisitRenewIamSessionResponse(w http.ResponseWriter) error
}

type RenewIamSession200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type RenewIamSession200JSONResponse struct {
	Body    SessionResponse
	Headers RenewIamSession200ResponseHeaders
}

func (response RenewIamSession200JSONResponse) VisitRenewIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RenewIamSession401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response RenewIamSession401ApplicationProblemPlusJSONResponse) VisitRenewIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RenewIamSession403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response RenewIamSession403ApplicationProblemPlusJSONResponse) VisitRenewIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RenewIamSession500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response RenewIamSession500ApplicationProblemPlusJSONResponse) VisitRenewIamSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ChangeIamAccountPassword Replace the authenticated account password
	// (PUT /iam/account/password)
	ChangeIamAccountPassword(ctx context.Context, request ChangeIamAccountPasswordRequestObject) (ChangeIamAccountPasswordResponseObject, error)
	// GetIamAccountProfile Read the authenticated account profile
	// (GET /iam/account/profile)
	GetIamAccountProfile(ctx context.Context, request GetIamAccountProfileRequestObject) (GetIamAccountProfileResponseObject, error)
	// UpdateIamAccountProfile Update the authenticated account profile
	// (PATCH /iam/account/profile)
	UpdateIamAccountProfile(ctx context.Context, request UpdateIamAccountProfileRequestObject) (UpdateIamAccountProfileResponseObject, error)
	// GetCurrentIamSession Read the current session without mutating it
	// (GET /iam/session/current)
	GetCurrentIamSession(ctx context.Context, request GetCurrentIamSessionRequestObject) (GetCurrentIamSessionResponseObject, error)
	// HeartbeatIamSession Extend idle expiry for an active session
	// (POST /iam/session/heartbeat)
	HeartbeatIamSession(ctx context.Context, request HeartbeatIamSessionRequestObject) (HeartbeatIamSessionResponseObject, error)
	// LoginIamSession Start an authenticated session
	// (POST /iam/session/login)
	LoginIamSession(ctx context.Context, request LoginIamSessionRequestObject) (LoginIamSessionResponseObject, error)
	// LogoutIamSession Revoke the current session
	// (POST /iam/session/logout)
	LogoutIamSession(ctx context.Context, request LogoutIamSessionRequestObject) (LogoutIamSessionResponseObject, error)
	// RenewIamSession Renew an active session while preserving its family CSRF token
	// (POST /iam/session/renew)
	RenewIamSession(ctx context.Context, request RenewIamSessionRequestObject) (RenewIamSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ChangeIamAccountPassword operation middleware
func (sh *strictHandler) ChangeIamAccountPassword(w http.ResponseWriter, r *http.Request) {
	var request ChangeIamAccountPasswordRequestObject

	var body ChangeIamAccountPasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangeIamAccountPassword(ctx, request.(ChangeIamAccountPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangeIamAccountPassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangeIamAccountPasswordResponseObject); ok {
		if err := validResponse.VisitChangeIamAccountPasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIamAccountProfile operation middleware
func (sh *strictHandler) GetIamAccountProfile(w http.ResponseWriter, r *http.Request) {
	var request GetIamAccountProfileRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIamAccountProfile(ctx, request.(GetIamAccountProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIamAccountProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIamAccountProfileResponseObject); ok {
		if err := validResponse.VisitGetIamAccountProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateIamAccountProfile operation middleware
func (sh *strictHandler) UpdateIamAccountProfile(w http.ResponseWriter, r *http.Request) {
	var request UpdateIamAccountProfileRequestObject

	var body UpdateIamAccountProfileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIamAccountProfile(ctx, request.(UpdateIamAccountProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIamAccountProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateIamAccountProfileResponseObject); ok {
		if err := validResponse.VisitUpdateIamAccountProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentIamSession operation middleware
func (sh *strictHandler) GetCurrentIamSession(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentIamSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentIamSession(ctx, request.(GetCurrentIamSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentIamSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentIamSessionResponseObject); ok {
		if err := validResponse.VisitGetCurrentIamSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeartbeatIamSession operation middleware
func (sh *strictHandler) HeartbeatIamSession(w http.ResponseWriter, r *http.Request) {
	var request HeartbeatIamSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeartbeatIamSession(ctx, request.(HeartbeatIamSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeartbeatIamSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeartbeatIamSessionResponseObject); ok {
		if err := validResponse.VisitHeartbeatIamSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginIamSession operation middleware
func (sh *strictHandler) LoginIamSession(w http.ResponseWriter, r *http.Request) {
	var request LoginIamSessionRequestObject

	var body LoginIamSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginIamSession(ctx, request.(LoginIamSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginIamSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginIamSessionResponseObject); ok {
		if err := validResponse.VisitLoginIamSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutIamSession operation middleware
func (sh *strictHandler) LogoutIamSession(w http.ResponseWriter, r *http.Request) {
	var request LogoutIamSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutIamSession(ctx, request.(LogoutIamSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutIamSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutIamSessionResponseObject); ok {
		if err := validResponse.VisitLogoutIamSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RenewIamSession operation middleware
func (sh *strictHandler) RenewIamSession(w http.ResponseWriter, r *http.Request) {
	var request RenewIamSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RenewIamSession(ctx, request.(RenewIamSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RenewIamSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RenewIamSessionResponseObject); ok {
		if err := validResponse.VisitRenewIamSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
