// Package filestransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package filestransport

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FileMetadataMediaType.
const (
	Applicationpdf FileMetadataMediaType = "application/pdf"
	Imagejpeg      FileMetadataMediaType = "image/jpeg"
	Imagepng       FileMetadataMediaType = "image/png"
	Textplain      FileMetadataMediaType = "text/plain"
)

// Valid indicates whether the value is a known member of the FileMetadataMediaType enum.
func (e FileMetadataMediaType) Valid() bool {
	switch e {
	case Applicationpdf:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Textplain:
		return true
	default:
		return false
	}
}

// Defines values for FileSort.
const (
	CreatedAt FileSort = "createdAt"
	Name      FileSort = "name"
	SizeBytes FileSort = "sizeBytes"
)

// Valid indicates whether the value is a known member of the FileSort enum.
func (e FileSort) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Name:
		return true
	case SizeBytes:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// Defines values for SortDirection.
const (
	Ascending  SortDirection = "ascending"
	Descending SortDirection = "descending"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
	switch e {
	case Ascending:
		return true
	case Descending:
		return true
	default:
		return false
	}
}

// DeleteFileTarget defines model for DeleteFileTarget.
type DeleteFileTarget struct {
	Id       openapi_types.UUID `json:"id"`
	Revision int64              `json:"revision"`
}

// DeleteFilesRequest defines model for DeleteFilesRequest.
type DeleteFilesRequest struct {
	Files []DeleteFileTarget `json:"files"`
}

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	CreatedAt    time.Time             `json:"createdAt"`
	Id           openapi_types.UUID    `json:"id"`
	MediaType    FileMetadataMediaType `json:"mediaType"`
	OriginalName string                `json:"originalName"`
	Revision     int64                 `json:"revision"`
	Sha256       string                `json:"sha256"`
	SizeBytes    int64                 `json:"sizeBytes"`
	UpdatedAt    time.Time             `json:"updatedAt"`
}

// FileMetadataMediaType defines model for FileMetadata.MediaType.
type FileMetadataMediaType string

// FilePage defines model for FilePage.
type FilePage struct {
	Rows  []FileMetadata `json:"rows"`
	Total int            `json:"total"`
}

// FileSort defines model for FileSort.
type FileSort string

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// SortDirection defines model for SortDirection.
type SortDirection string

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// FileId defines model for FileId.
type FileId = openapi_types.UUID

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// CapacityProblem defines model for CapacityProblem.
type CapacityProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// ContentProblem defines model for ContentProblem.
type ContentProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Search    *string        `form:"search,omitempty" json:"search,omitempty"`
	Page      int            `form:"page" json:"page"`
	PageSize  int            `form:"pageSize" json:"pageSize"`
	Sort      *FileSort      `form:"sort,omitempty" json:"sort,omitempty"`
	Direction *SortDirection `form:"direction,omitempty" json:"direction,omitempty"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// DeleteFilesJSONRequestBody defines body for DeleteFiles for application/json ContentType.
type DeleteFilesJSONRequestBody = DeleteFilesRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListFiles List file metadata in the caller data scope
	// (GET /files/objects)
	ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams)
	// UploadFile Stream one file into private local storage
	// (POST /files/objects)
	UploadFile(w http.ResponseWriter, r *http.Request)
	// DeleteFiles Delete file metadata and content atomically from the public projection
	// (POST /files/objects/batch-delete)
	DeleteFiles(w http.ResponseWriter, r *http.Request)
	// GetFileMetadata Read one authorized metadata record
	// (GET /files/objects/{fileId})
	GetFileMetadata(w http.ResponseWriter, r *http.Request, fileId FileId)
	// DownloadFile Stream content after a fresh authorization decision
	// (GET /files/objects/{fileId}/content)
	DownloadFile(w http.ResponseWriter, r *http.Request, fileId FileId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListFiles List file metadata in the caller data scope
// (GET /files/objects)
func (_ Unimplemented) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UploadFile Stream one file into private local storage
// (POST /files/objects)
func (_ Unimplemented) UploadFile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteFiles Delete file metadata and content atomically from the public projection
// (POST /files/objects/batch-delete)
func (_ Unimplemented) DeleteFiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetFileMetadata Read one authorized metadata record
// (GET /files/objects/{fileId})
func (_ Unimplemented) GetFileMetadata(w http.ResponseWriter, r *http.Request, fileId FileId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DownloadFile Stream content after a fresh authorization decision
// (GET /files/objects/{fileId}/content)
func (_ Unimplemented) DownloadFile(w http.ResponseWriter, r *http.Request, fileId FileId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListFiles operation middleware
func (siw *ServerInterfaceWrapper) ListFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Required query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", r.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "direction"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadFile operation middleware
func (siw *ServerInterfaceWrapper) UploadFile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadFile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFiles operation middleware
func (siw *ServerInterfaceWrapper) DeleteFiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFileMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetFileMetadata(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "fileId" -------------
	var fileId FileId

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", chi.URLParam(r, "fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFileMetadata(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadFile operation middleware
func (siw *ServerInterfaceWrapper) DownloadFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "fileId" -------------
	var fileId FileId

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", chi.URLParam(r, "fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/objects", wrapper.ListFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/objects", wrapper.UploadFile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/objects/batch-delete", wrapper.DeleteFiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/objects/{fileId}", wrapper.GetFileMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/objects/{fileId}/content", wrapper.DownloadFile)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type AuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizationProblemResponseHeaders
}

type CapacityProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type CapacityProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers CapacityProblemResponseHeaders
}

type ConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictProblemResponseHeaders
}

type ContentProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ContentProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ContentProblemResponseHeaders
}

type InternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type InternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalProblemResponseHeaders
}

type NotFoundProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type NotFoundProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers NotFoundProblemResponseHeaders
}

type ValidationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ValidationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ValidationProblemResponseHeaders
}

type ListFilesRequestObject struct {
	Params ListFilesParams
}

type ListFilesResponseObject interface {
	VisitListFilesResponse(w http.ResponseWriter) error
}

type ListFiles200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type ListFiles200JSONResponse struct {
	Body    FilePage
	Headers ListFiles200ResponseHeaders
}

func (response ListFiles200JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFiles400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListFiles400ApplicationProblemPlusJSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListFiles401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListFiles401ApplicationProblemPlusJSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListFiles403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListFiles403ApplicationProblemPlusJSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListFiles500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListFiles500ApplicationProblemPlusJSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFileRequestObject struct {
	Body *multipart.Reader
}

type UploadFileResponseObject interface {
	VisitUploadFileResponse(w http.ResponseWriter) error
}

type UploadFile201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type UploadFile201JSONResponse struct {
	Body    FileMetadata
	Headers UploadFile201ResponseHeaders
}

func (response UploadFile201JSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile400ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile401ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile403ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile409ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile413ApplicationProblemPlusJSONResponse struct {
	ContentProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile413ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile415ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type UploadFile415ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers UploadFile415ResponseHeaders
}

func (response UploadFile415ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile500ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadFile507ApplicationProblemPlusJSONResponse struct {
	CapacityProblemApplicationProblemPlusJSONResponse
}

func (response UploadFile507ApplicationProblemPlusJSONResponse) VisitUploadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(507)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFilesRequestObject struct {
	Body *DeleteFilesJSONRequestBody
}

type DeleteFilesResponseObject interface {
	VisitDeleteFilesResponse(w http.ResponseWriter) error
}

type DeleteFiles204ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type DeleteFiles204Response struct {
	Headers DeleteFiles204ResponseHeaders
}

func (response DeleteFiles204Response) VisitDeleteFilesResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(204)
	return nil
}

type DeleteFiles400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles400ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFiles401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles401ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFiles403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles403ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFiles404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles404ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFiles409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles409ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFiles500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DeleteFiles500ApplicationProblemPlusJSONResponse) VisitDeleteFilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadataRequestObject struct {
	FileId FileId `json:"fileId"`
}

type GetFileMetadataResponseObject interface {
	VisitGetFileMetadataResponse(w http.ResponseWriter) error
}

type GetFileMetadata200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetFileMetadata200JSONResponse struct {
	Body    FileMetadata
	Headers GetFileMetadata200ResponseHeaders
}

func (response GetFileMetadata200JSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadata400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response GetFileMetadata400ApplicationProblemPlusJSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadata401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetFileMetadata401ApplicationProblemPlusJSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadata403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response GetFileMetadata403ApplicationProblemPlusJSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadata404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response GetFileMetadata404ApplicationProblemPlusJSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetFileMetadata500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetFileMetadata500ApplicationProblemPlusJSONResponse) VisitGetFileMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadFileRequestObject struct {
	FileId FileId `json:"fileId"`
}

type DownloadFileResponseObject interface {
	VisitDownloadFileResponse(w http.ResponseWriter) error
}

type DownloadFile200ResponseHeaders struct {
	ContentDisposition  string
	SetCookie           *string
	XCSRFToken          string
	XContentTypeOptions string
}

type DownloadFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadFile200ResponseHeaders
	ContentLength int64
}

func (response DownloadFile200ApplicationoctetStreamResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.Header().Set("X-Content-Type-Options", fmt.Sprint(response.Headers.XContentTypeOptions))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadFile400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response DownloadFile400ApplicationProblemPlusJSONResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadFile401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DownloadFile401ApplicationProblemPlusJSONResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadFile403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DownloadFile403ApplicationProblemPlusJSONResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadFile404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DownloadFile404ApplicationProblemPlusJSONResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadFile500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DownloadFile500ApplicationProblemPlusJSONResponse) VisitDownloadFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListFiles List file metadata in the caller data scope
	// (GET /files/objects)
	ListFiles(ctx context.Context, request ListFilesRequestObject) (ListFilesResponseObject, error)
	// UploadFile Stream one file into private local storage
	// (POST /files/objects)
	UploadFile(ctx context.Context, request UploadFileRequestObject) (UploadFileResponseObject, error)
	// DeleteFiles Delete file metadata and content atomically from the public projection
	// (POST /files/objects/batch-delete)
	DeleteFiles(ctx context.Context, request DeleteFilesRequestObject) (DeleteFilesResponseObject, error)
	// GetFileMetadata Read one authorized metadata record
	// (GET /files/objects/{fileId})
	GetFileMetadata(ctx context.Context, request GetFileMetadataRequestObject) (GetFileMetadataResponseObject, error)
	// DownloadFile Stream content after a fresh authorization decision
	// (GET /files/objects/{fileId}/content)
	DownloadFile(ctx context.Context, request DownloadFileRequestObject) (DownloadFileResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListFiles operation middleware
func (sh *strictHandler) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	var request ListFilesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFiles(ctx, request.(ListFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFilesResponseObject); ok {
		if err := validResponse.VisitListFilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadFile operation middleware
func (sh *strictHandler) UploadFile(w http.ResponseWriter, r *http.Request) {
	var request UploadFileRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadFile(ctx, request.(UploadFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadFileResponseObject); ok {
		if err := validResponse.VisitUploadFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFiles operation middleware
func (sh *strictHandler) DeleteFiles(w http.ResponseWriter, r *http.Request) {
	var request DeleteFilesRequestObject

	var body DeleteFilesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFiles(ctx, request.(DeleteFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFilesResponseObject); ok {
		if err := validResponse.VisitDeleteFilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFileMetadata operation middleware
func (sh *strictHandler) GetFileMetadata(w http.ResponseWriter, r *http.Request, fileId FileId) {
	var request GetFileMetadataRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFileMetadata(ctx, request.(GetFileMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFileMetadata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFileMetadataResponseObject); ok {
		if err := validResponse.VisitGetFileMetadataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadFile operation middleware
func (sh *strictHandler) DownloadFile(w http.ResponseWriter, r *http.Request, fileId FileId) {
	var request DownloadFileRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadFile(ctx, request.(DownloadFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadFileResponseObject); ok {
		if err := validResponse.VisitDownloadFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
