// Package audittransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package audittransport

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActorType.
const (
	Account ActorType = "account"
	System  ActorType = "system"
)

// Valid indicates whether the value is a known member of the ActorType enum.
func (e ActorType) Valid() bool {
	switch e {
	case Account:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for AuditAction.
const (
	AuditActionCreate AuditAction = "create"
	AuditActionDelete AuditAction = "delete"
	AuditActionLogin  AuditAction = "login"
	AuditActionUpdate AuditAction = "update"
)

// Valid indicates whether the value is a known member of the AuditAction enum.
func (e AuditAction) Valid() bool {
	switch e {
	case AuditActionCreate:
		return true
	case AuditActionDelete:
		return true
	case AuditActionLogin:
		return true
	case AuditActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for AuditKind.
const (
	AuditKindLogin     AuditKind = "login"
	AuditKindOperation AuditKind = "operation"
)

// Valid indicates whether the value is a known member of the AuditKind enum.
func (e AuditKind) Valid() bool {
	switch e {
	case AuditKindLogin:
		return true
	case AuditKindOperation:
		return true
	default:
		return false
	}
}

// Defines values for AuditOutcome.
const (
	Failed    AuditOutcome = "failed"
	Succeeded AuditOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the AuditOutcome enum.
func (e AuditOutcome) Valid() bool {
	switch e {
	case Failed:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for AuditSource.
const (
	Desktop AuditSource = "desktop"
	Server  AuditSource = "server"
	Web     AuditSource = "web"
)

// Valid indicates whether the value is a known member of the AuditSource enum.
func (e AuditSource) Valid() bool {
	switch e {
	case Desktop:
		return true
	case Server:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for CleanupAuditRequestConfirmation.
const (
	DeleteExpiredAuditRecords CleanupAuditRequestConfirmation = "delete-expired-audit-records"
)

// Valid indicates whether the value is a known member of the CleanupAuditRequestConfirmation enum.
func (e CleanupAuditRequestConfirmation) Valid() bool {
	switch e {
	case DeleteExpiredAuditRecords:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// ActorType defines model for ActorType.
type ActorType string

// AuditAction defines model for AuditAction.
type AuditAction string

// AuditFact defines model for AuditFact.
type AuditFact struct {
	Action     AuditAction  `json:"action"`
	ActorRef   *string      `json:"actorRef,omitempty"`
	ActorType  ActorType    `json:"actorType"`
	EventId    *string      `json:"eventId,omitempty"`
	Id         string       `json:"id"`
	Kind       AuditKind    `json:"kind"`
	OccurredAt time.Time    `json:"occurredAt"`
	Operation  *string      `json:"operation,omitempty"`
	Outcome    AuditOutcome `json:"outcome"`
	Source     AuditSource  `json:"source"`
	Subject    string       `json:"subject"`
	TraceId    *string      `json:"traceId,omitempty"`
}

// AuditKind defines model for AuditKind.
type AuditKind string

// AuditOutcome defines model for AuditOutcome.
type AuditOutcome string

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
	Records  []AuditFact `json:"records"`
	Total    int         `json:"total"`
}

// AuditSource defines model for AuditSource.
type AuditSource string

// CleanupAuditRequest defines model for CleanupAuditRequest.
type CleanupAuditRequest struct {
	Before       time.Time                       `json:"before"`
	Confirmation CleanupAuditRequestConfirmation `json:"confirmation"`
}

// CleanupAuditRequestConfirmation defines model for CleanupAuditRequest.Confirmation.
type CleanupAuditRequestConfirmation string

// CleanupAuditResponse defines model for CleanupAuditResponse.
type CleanupAuditResponse struct {
	Deleted      int  `json:"deleted"`
	MoreEligible bool `json:"moreEligible"`
}

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizedAuthorizationProblem defines model for AuthorizedAuthorizationProblem.
type AuthorizedAuthorizationProblem = Problem

// AuthorizedConflictProblem defines model for AuthorizedConflictProblem.
type AuthorizedConflictProblem = Problem

// AuthorizedInternalProblem defines model for AuthorizedInternalProblem.
type AuthorizedInternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ListAuditRecordsParams defines parameters for ListAuditRecords.
type ListAuditRecordsParams struct {
	Page     int           `form:"page" json:"page"`
	PageSize int           `form:"pageSize" json:"pageSize"`
	Kind     *AuditKind    `form:"kind,omitempty" json:"kind,omitempty"`
	Action   *AuditAction  `form:"action,omitempty" json:"action,omitempty"`
	Outcome  *AuditOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`
	Source   *AuditSource  `form:"source,omitempty" json:"source,omitempty"`
	From     *time.Time    `form:"from,omitempty" json:"from,omitempty"`
	To       *time.Time    `form:"to,omitempty" json:"to,omitempty"`
}

// CleanupAuditRecordsJSONRequestBody defines body for CleanupAuditRecords for application/json ContentType.
type CleanupAuditRecordsJSONRequestBody = CleanupAuditRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAuditRecords List authorized audit facts
	// (GET /audit/records)
	ListAuditRecords(w http.ResponseWriter, r *http.Request, params ListAuditRecordsParams)
	// CleanupAuditRecords Delete one bounded batch of retention-eligible audit facts
	// (POST /audit/records/cleanup)
	CleanupAuditRecords(w http.ResponseWriter, r *http.Request)
	// GetAuditRecord Read one authorized audit fact
	// (GET /audit/records/{id})
	GetAuditRecord(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAuditRecords List authorized audit facts
// (GET /audit/records)
func (_ Unimplemented) ListAuditRecords(w http.ResponseWriter, r *http.Request, params ListAuditRecordsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CleanupAuditRecords Delete one bounded batch of retention-eligible audit facts
// (POST /audit/records/cleanup)
func (_ Unimplemented) CleanupAuditRecords(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuditRecord Read one authorized audit fact
// (GET /audit/records/{id})
func (_ Unimplemented) GetAuditRecord(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAuditRecords operation middleware
func (siw *ServerInterfaceWrapper) ListAuditRecords(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditRecordsParams

	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Required query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "outcome" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "outcome", r.URL.Query(), &params.Outcome, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "outcome"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "outcome", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CleanupAuditRecords operation middleware
func (siw *ServerInterfaceWrapper) CleanupAuditRecords(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CleanupAuditRecords(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditRecord operation middleware
func (siw *ServerInterfaceWrapper) GetAuditRecord(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditRecord(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/audit/records", wrapper.ListAuditRecords)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/audit/records/cleanup", wrapper.CleanupAuditRecords)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/audit/records/{id}", wrapper.GetAuditRecord)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizedAuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type AuthorizedAuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizedAuthorizationProblemResponseHeaders
}

type AuthorizedConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type AuthorizedConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizedConflictProblemResponseHeaders
}

type AuthorizedInternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type AuthorizedInternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizedInternalProblemResponseHeaders
}

type NotFoundProblemApplicationProblemPlusJSONResponse Problem

type ValidationProblemApplicationProblemPlusJSONResponse Problem

type ListAuditRecordsRequestObject struct {
	Params ListAuditRecordsParams
}

type ListAuditRecordsResponseObject interface {
	VisitListAuditRecordsResponse(w http.ResponseWriter) error
}

type ListAuditRecords200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type ListAuditRecords200JSONResponse struct {
	Body    AuditPage
	Headers ListAuditRecords200ResponseHeaders
}

func (response ListAuditRecords200JSONResponse) VisitListAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditRecords400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditRecords400ApplicationProblemPlusJSONResponse) VisitListAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditRecords401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditRecords401ApplicationProblemPlusJSONResponse) VisitListAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditRecords403ApplicationProblemPlusJSONResponse struct {
	AuthorizedAuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditRecords403ApplicationProblemPlusJSONResponse) VisitListAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditRecords500ApplicationProblemPlusJSONResponse struct {
	AuthorizedInternalProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditRecords500ApplicationProblemPlusJSONResponse) VisitListAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecordsRequestObject struct {
	Body *CleanupAuditRecordsJSONRequestBody
}

type CleanupAuditRecordsResponseObject interface {
	VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error
}

type CleanupAuditRecords200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type CleanupAuditRecords200JSONResponse struct {
	Body    CleanupAuditResponse
	Headers CleanupAuditRecords200ResponseHeaders
}

func (response CleanupAuditRecords200JSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecords400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response CleanupAuditRecords400ApplicationProblemPlusJSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecords401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response CleanupAuditRecords401ApplicationProblemPlusJSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecords403ApplicationProblemPlusJSONResponse struct {
	AuthorizedAuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response CleanupAuditRecords403ApplicationProblemPlusJSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecords409ApplicationProblemPlusJSONResponse struct {
	AuthorizedConflictProblemApplicationProblemPlusJSONResponse
}

func (response CleanupAuditRecords409ApplicationProblemPlusJSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CleanupAuditRecords500ApplicationProblemPlusJSONResponse struct {
	AuthorizedInternalProblemApplicationProblemPlusJSONResponse
}

func (response CleanupAuditRecords500ApplicationProblemPlusJSONResponse) VisitCleanupAuditRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecordRequestObject struct {
	Id string `json:"id"`
}

type GetAuditRecordResponseObject interface {
	VisitGetAuditRecordResponse(w http.ResponseWriter) error
}

type GetAuditRecord200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetAuditRecord200JSONResponse struct {
	Body    AuditFact
	Headers GetAuditRecord200ResponseHeaders
}

func (response GetAuditRecord200JSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecord400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response GetAuditRecord400ApplicationProblemPlusJSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecord401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetAuditRecord401ApplicationProblemPlusJSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecord403ApplicationProblemPlusJSONResponse struct {
	AuthorizedAuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response GetAuditRecord403ApplicationProblemPlusJSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecord404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response GetAuditRecord404ApplicationProblemPlusJSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditRecord500ApplicationProblemPlusJSONResponse struct {
	AuthorizedInternalProblemApplicationProblemPlusJSONResponse
}

func (response GetAuditRecord500ApplicationProblemPlusJSONResponse) VisitGetAuditRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAuditRecords List authorized audit facts
	// (GET /audit/records)
	ListAuditRecords(ctx context.Context, request ListAuditRecordsRequestObject) (ListAuditRecordsResponseObject, error)
	// CleanupAuditRecords Delete one bounded batch of retention-eligible audit facts
	// (POST /audit/records/cleanup)
	CleanupAuditRecords(ctx context.Context, request CleanupAuditRecordsRequestObject) (CleanupAuditRecordsResponseObject, error)
	// GetAuditRecord Read one authorized audit fact
	// (GET /audit/records/{id})
	GetAuditRecord(ctx context.Context, request GetAuditRecordRequestObject) (GetAuditRecordResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAuditRecords operation middleware
func (sh *strictHandler) ListAuditRecords(w http.ResponseWriter, r *http.Request, params ListAuditRecordsParams) {
	var request ListAuditRecordsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditRecords(ctx, request.(ListAuditRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditRecordsResponseObject); ok {
		if err := validResponse.VisitListAuditRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CleanupAuditRecords operation middleware
func (sh *strictHandler) CleanupAuditRecords(w http.ResponseWriter, r *http.Request) {
	var request CleanupAuditRecordsRequestObject

	var body CleanupAuditRecordsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CleanupAuditRecords(ctx, request.(CleanupAuditRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CleanupAuditRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CleanupAuditRecordsResponseObject); ok {
		if err := validResponse.VisitCleanupAuditRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuditRecord operation middleware
func (sh *strictHandler) GetAuditRecord(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAuditRecordRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuditRecord(ctx, request.(GetAuditRecordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuditRecord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuditRecordResponseObject); ok {
		if err := validResponse.VisitGetAuditRecordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
